"""Photo storage: validating uploads and writing them to disk.

Files live on the filesystem and only their metadata goes in SQLite — an image
in a database row costs a base64 round trip on every read and bloats a file the
rest of the app wants small.

Everything an uploader controls is treated as hostile:

* **The filename is never used.** Stored names are generated UUIDs with an
  extension derived from the sniffed type, so "../../app/main.py" or a name
  that collides with an existing file cannot happen by construction.
* **The declared Content-Type is never trusted.** The format is decided by the
  file's own magic bytes; a .php or .svg renamed to .jpg fails that check.
* **The size limit is enforced while streaming**, not after. Reading an
  arbitrarily large upload into memory to measure it is the denial of service
  the limit exists to prevent.
"""

import os
import uuid
from pathlib import Path

from app.config import ALLOWED_PHOTO_TYPES, PHOTO_MAGIC_BYTES, max_photo_bytes, upload_dir

# Enough to cover the longest signature we check.
_SNIFF_BYTES = 16


class PhotoRejected(Exception):
    """An upload failed validation. The message is safe to show a user."""


def sniff_type(head: bytes) -> str | None:
    """Identify an allowed image format from its leading bytes, or None."""
    for content_type, signatures in PHOTO_MAGIC_BYTES.items():
        for signature in signatures:
            if head.startswith(signature):
                # RIFF alone is any RIFF container (.wav among them); the WEBP
                # marker at offset 8 is what makes it an image.
                if content_type == "image/webp" and head[8:12] != b"WEBP":
                    continue
                return content_type
    return None


def storage_root() -> Path:
    root = Path(upload_dir())
    root.mkdir(parents=True, exist_ok=True)
    return root


def path_for(stored_name: str) -> Path:
    """Resolve a stored filename to its path, refusing anything that escapes.

    Stored names are generated by this module, so a name that fails this check
    means the database row was tampered with — worth refusing loudly rather than
    serving whatever file it points at.
    """
    root = storage_root().resolve()
    candidate = (root / stored_name).resolve()
    if candidate.parent != root:
        raise PhotoRejected("invalid photo path")
    return candidate


def save_upload(read_chunk, declared_type: str | None) -> tuple[str, str, int]:
    """Stream an upload to disk. Returns (stored_name, content_type, size).

    `read_chunk` is an awaitable-free callable returning bytes, mirroring the
    chunked reads of a file-like object; an empty result ends the stream.

    Raises PhotoRejected without leaving a file behind if the upload is empty,
    too large, or not one of the allowed image formats.
    """
    limit = max_photo_bytes()

    first = read_chunk(_SNIFF_BYTES)
    if not first:
        raise PhotoRejected("the uploaded file is empty")

    content_type = sniff_type(first)
    if content_type is None:
        allowed = ", ".join(sorted(ALLOWED_PHOTO_TYPES))
        raise PhotoRejected(f"unsupported image format — allowed types are {allowed}")

    stored_name = f"{uuid.uuid4().hex}{ALLOWED_PHOTO_TYPES[content_type]}"
    destination = path_for(stored_name)

    size = 0
    try:
        with open(destination, "wb") as out:
            chunk = first
            while chunk:
                size += len(chunk)
                if size > limit:
                    raise PhotoRejected(
                        f"image is larger than the {limit // (1024 * 1024)} MB limit"
                    )
                out.write(chunk)
                chunk = read_chunk(64 * 1024)
    except Exception:
        # Never leave a partial or oversized file on disk.
        destination.unlink(missing_ok=True)
        raise

    return stored_name, content_type, size


def delete_file(stored_name: str) -> None:
    """Remove a stored file. Missing is fine — the goal is that it is gone."""
    try:
        path_for(stored_name).unlink(missing_ok=True)
    except PhotoRejected:
        # A malformed name points at nothing we own; nothing to delete.
        pass


def public_url(photo_id: int) -> str:
    """The URL a browser loads this photo from.

    A route rather than a static mount, so serving stays in front of the
    database row and a deleted photo stops resolving immediately.
    """
    return f"/api/photos/{photo_id}"
